# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.12'

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: E5k1v5E1q+1i72QT/bDxlVh42PfWu2HpHOYAwVQH/SJP3VpgY9j6dgrrT9CcgiHuzH33K0IrKpvFr7g7MvxO3I/M0RYBGyXT1LnojJtYMh6ouH0kQGrBnY9mnnjiY3ggh25Cw3S75YPLVxCT1yZ2APAc6cAlG3MhydXI9T9iCW/ZFw45vJI7R78TNMQDxwfbTuvTNbhjQ0Bb6cBhjMpgyakbGyR1eBXrri0b+y47YnKBtw10IHeI+3S9m6FpesGEI8mbPDCd6DKtAHH8g0EflMMtM+NDyI1BK9PHymKZrIaJm6a7i0PjTfD4X12K1FhFTHOfPolHRvd7O1fu9jGypSJo95dG2xcwPK/yUKboUTMbax3Hy5AknXhAVlGcQiti+7OYrtilA3IkZhfGOsUd9UeqFA2QKAdVaPJEJi2RKUramnezqj2P6WP9rMiMzo4HhRtOSBZCD32sbxcLZ+FGoJOHDckwWcg9Cnovahm/yux6b8dalSpSrt/S5ddDRi/MiEwQBJ4SopsZU5Tdi6WYWlW4BjRcSR/8miVA391wAiyQyCIKRqZARo29n47QcAkS/zgB9h+SR7OcIQKl8GkkL6+QaqoaBijlPhEtiYYhnfJkGieTqZAGVa/SRy+V9lEvZz5hoZNS7fdzYRgLK/nz6yqEurCNDuhxfxHVxRzgXBU=
    # SAUCE_TOKENS
    - secure: OTLsvV0PILnX2uN8/wX0QvNm6uD25RERC4IwgB185lSbJTZuaFKQsrLUxBTkCoCNn3wdy5mIr7VR03tnWXw6b44jtnIrZp+IdHuYxGwd5RyjMPhryilzPGJL8uPqVSTJPXo+DQpMAomUlRbi9+Y9kmMqRwn4+Pdh+mxqigrbv73mT/EZ5fzDKzNviQgVsC4wPhb+RMA058KjU+mOQM+rrNnKwmbHFw73sKPvM1xY1q/saA7IRtwWPQyDZYMbwsHgsf+6ejluMowV0apdXcIOgJ1dlY6vMNHhMOejYXXJcRx6CtzOE7ZYa0fPa0AkLLTXoDxEeiadZPsTJGYkXNnPgex2wS9obSXYpT9oEu83HACKYBQk6s8B9a+BwD1thouhDA1IxbdrE1fWk2oXzRnhYdiOqyb+JAHmx8zx40O2RsCko29OX+dVjD1dDoUPBlfWruw6v5SZXinGSNUnRIc4QwSHcam1bmRajKvd4PBb+DssFw3XxDlNbT2RzhWSYsSi6RCSXxf46EkT6DthxS9VEtzATHdN3MAGQbnZJgxqQbyUGzztRNsMm/eOupBbCBSPuUBnZ/ccW+I6Yyi7GFURLSJ+tWAHRSX8/cehO5NLCJC3mH+KDai/oA1+NL0YNzxiGlVJ9shPNNimgF4mx4mNQQY+B5uEwiBLIsCxQziwKAE=
    - secure: CYpCRl9WcIqiq4j8U7ZItNMJRwt+qJNeWdwMe1VfUQ+5KbZcf5OQgO8t3KFZBiCXRDIyOuU5QK1xNx659dVmdYDbOmcOPz1tcWI8GGYwfddU+Hg2UmVWnxdYiba5f1de4I63f9SmbtIbW3mLUhm3SXxvV9hAJZBJqWW+Zp1AGuCHHKkz+IBQl8Yj4PCyAO1xysmemov+RoT4IR9xXrgW8LJ7c048b30LXVwGscpPf7ShoB0tSu8pGWMCtmUL/O8gTeN11lz2fS60gnVp8lA2snKwhSrdlC+IMoqWbSnd7FofF287z9TXQedybpXTJuFjPOTRwz/H7slcvKkJqn9Q2OiGtK9MAw5hIwep58lVDx4oIMPfOLs4bD4ufKzBuOMfaniO0ER0Iwb7Pr1C4GKQSZv9McaE3O1coqCjtO8wXHQiw5H+WSZQTv18RIddPI9eGio2Ndpux/SLohNHEMu86C+f3pCMihzrqNFxbOWj1rQWK0BLgrl8lU5Kul7flTr5m43vC/mtM24BTz7jdVSZ1otGpbV1M6YQCNOmtuXNWcNcAol1CpGT1RJJUCGcRdGtjnV4MTbpmhEkVzx/elguWH+bwRpJMxwMHm+Zqa0JE28qZUv6tRyIBXl/yX6MNOcLS0RKhIk7bRHu8XEEY+xKahdIZRskpOViuMiEQWGB2h8=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: NH67lLo7mXuJni3QhxFbllhLmaEJBMuz6DnikZ1aSVYtpiuyBCt2sgodA1FRmvVM4tj2ZzXdfBQ49rp3GEbkjc3pacs35egX/FGp/MuoU69piQEM5jDdnOVU8rNIEqFiYhlzMGhgkVOH3IL+aKuWmDxHxgt8XJiFlIURIqjPKqGJMNw54uuYhRtFc3PjdYdyo++JodV2cg62lyILoZD9Jis75MOb+/IuLxRJuOiZSZX8ipSA6uno9vAjcKES5xbBocQA5bPw/V/Lk89QfBjbzaheehbCPN7tD59gDghmFropx9JGOSrqxctBDVMayhLe0i3I7fvtJytTdeCbtZZhBYAsAZv8l6SI8QpUTbZvfUxLcBEXSrI2iTDLd+4Sh9jTM9z8EaBLxtxSg2Qzm0bklJiDaSmp0wb/RtDUx0alHyrmUxxpx6D+uJC/gTbrhxusXTWViKcBPjM2ZTaPAJjByVJvw3MY9FFkDVm8Wg9z8vtyd96Mr/XjCihWiE8PI+65xy4ZJmJyyrP0XnvJyFLn9j4RTUm5faILnpZv+Bqglg97cjPL+hL2aLnva/Tay/PXjdhEY25MuspZgWEmxH8+xZwXyCged70qxBYGAGqUKzSrTo/SBoz4jqRVM/851C32ltCqayU5DDywWCe57WhvJ57UQQEhc8WyhmelUsiAExs=

# Cloud testing
after_deploy:
  - npm install
  - npm install zuul --global
  - npm run test-cloud